"""empty message

Revision ID: 26dca7f82a8d
Revises: a3fe71198e83
Create Date: 2018-06-29 21:06:40.308474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26dca7f82a8d'
down_revision = 'a3fe71198e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('uploader', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'uploader')
    # ### end Alembic commands ###
